#!/bin/bash
set -e
sudo apt-get install -y python3.7
sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.7 1
sudo apt-get install -y mariadb-server libmariadb3 libmariadb-dev
sudo systemctl start mariadb.service        

pip install -Iv mariadb==1.0.6
pip install -Iv beautifultable==1.0.1
pip install -Iv RPi==0.0.1
git clone https://github.com/Falldog/pyconcrete
cd pyconcrete
printf "T3khnetos123\nT3khnetos123" | sudo python setup.py install
sudo cp /usr/local/bin/pyconcrete /usr/bin/
cd ..
sudo rm -rf pyconcrete/



echo $"export PATH=\$PATH:$(pwd)/Bash" >> ~/.bash_profile
echo $"export PATH=\$PATH:$(pwd)/" >> ~/.bash_profile
echo $"export MARIADB_USER=root" >> ~/.bash_profile
echo $"source ~/.bashrc" >> ~/.bash_profile
sed -i "s+/home/pi/Documents/.Hidden+$(pwd)+" Bash/snmpmonitor
sed -i "s+/home/pi/Documents/.Hidden+$(pwd)+" LuminariaSNMP/__init__.py