#!/bin/bash
set -e
sudo apt-get install -y python3.7
sudo apt-get install -y python3-pip
sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.7 1
sudo apt-get install -y mariadb-server libmariadb3 libmariadb-dev
sudo apt-get install -y snmp snmpd snmp-mibs-downloader
sudo systemctl start mariadb.service        

pip install -Iv mariadb==1.0.6 || pip3 install -Iv mariadb==1.0.6
pip install -Iv beautifultable==1.0.1 || pip3 install -Iv beautifultable==1.0.1
pip install -Iv RPi==0.0.1 || pip3 install -Iv RPi==0.0.1
git clone https://github.com/Falldog/pyconcrete
cd pyconcrete
printf "T3khnetos123\nT3khnetos123" | sudo python setup.py install
sudo cp /usr/local/bin/pyconcrete /usr/bin/
cd ..
sudo rm -rf pyconcrete/

printf $". ~/.profile
if [[ \$- == *i* ]]; then . ~/.bashrc; fi \n" >> ~/.bash_profile 
cd ..
ProyectoSNMP/Help/obfuscate ProyectoSNMP
cd SNMP
printf $"export PATH=\$PATH:$(pwd)/Bash\n" >> ~/.profile
sed -i "s+/home/pi/Documents/.Hidden+$(pwd)+" Bash/snmpmonitor
sed -i "s+/usr/bin/python3.7+/usr/bin/pyconcrete+" Bash/snmpmonitor
sed -i "s+\.py+\.pye+g" Bash/snmpmonitor
sed -i "s+/home/pi/Documents/.Hidden+$(pwd)+" Help/snmpmonitor-completion
sudo sed -i "s+mibs :+#mibs :+" /etc/snmp/snmp.conf
sudo cp Help/snmpmonitor-completion /etc/bash_completion.d/
