#!/bin/bash
EXECUTE="/usr/bin/python3.7"
PYTHONPATH="/home/pi/Documents/.Hidden/:$PATH"
PATH="/home/pi/Documents/.Hidden/:$PATH"
ROOT="/home/pi/Documents/.Hidden/LuminariaSNMP"
help(){
    echo "--add-interface       Añade interfaz al monitoreo (snmpmonitor --add <ip> <community>)"
    echo "--add-rack            Añade rack"
    echo "--available-pins      Muestra pines disponibles de la RPi"
    echo "--debug               Inicia el monitoreo con la salida estándar en la terminal"
    echo "--down-interfaces     Muestra las interfaces que se encuentran abajo actualmente"
    echo "--edit-rack           Edita datos de un rack"
    echo "--help                Muestra este mensaje"
    echo "--interfaces          Muestra las interfaces actuales en la lista de monitoreo y el rack donde se encuentran"
    echo "--log                 Muestra las últimas 50 entradas del log"
    echo "--racks               Muestra los racks guardados"
    echo "--remove-interface    Elimina interfaz del monitoreo"
    echo "--remove-rack         Elimina rack y todas las interfaces que lo contienen"
    echo "--restart             Reinicia el monitoreo"
    echo "--start               Inicia el proceso de monitoreo"
    echo "--status              Muestra si el monitoreo se encuentra activo actualmente"
    echo "--stop                Detiene el proceso de monitoreo"
}

case $1 in
    "--add-interface")  
        $EXECUTE $ROOT/Interfaces/add.py $2 $3
    ;;
    "--add-rack")
        $EXECUTE $ROOT/Racks/add.py
    ;;
    "--available-pins")
        $EXECUTE $ROOT/LEDStrip/available.py
    ;;
    "--debug")
        $EXECUTE $ROOT/Interfaces/start.py debug
    ;;
    "--down-interfaces")
        $EXECUTE $ROOT/Logs/down.py
    ;;
    "--edit-rack")
        $EXECUTE $ROOT/Racks/edit.py
    ;;
    "--help")
        help
    ;;
    "--interfaces")
        $EXECUTE $ROOT/Interfaces/active.py
    ;;
    "--log")
        $EXECUTE $ROOT/Logs/log.py
    ;;
    "--racks")
        $EXECUTE $ROOT/Racks/active.py
    ;;
    "--restart")
        $EXECUTE $ROOT/Interfaces/start.py restart
    ;;
    "--remove-interface")
        $EXECUTE $ROOT/Interfaces/remove.py
    ;;
    "--remove-rack")
        $EXECUTE $ROOT/Racks/remove.py
    ;;
    "--start")
        $EXECUTE $ROOT/Interfaces/start.py start
    ;;
    "--status")
        $EXECUTE $ROOT/Interfaces/start.py running
    ;;
    "--stop")
        $EXECUTE $ROOT/Interfaces/start.py stop
        
    ;;
    *)
        help
        
    ;;
esac
