#!/bin/bash
EXECUTE="/usr/bin/python3.7"
PROYECT="/home/pi/Documents/.Hidden"
export PYTHONPATH=$PROYECT
PATH="$PROYECT:$PATH"
ROOT="$PROYECT/LuminariaSNMP"
help(){
    cat $PROYECT/.Help/.help
}

case $1 in
    "--add-interface")  
        $EXECUTE $ROOT/Interfaces/add.py $2 $3
    ;;
    "--add-rack")
        $EXECUTE $ROOT/Racks/add.py
    ;;
    "--available-pins")
        $EXECUTE $ROOT/LEDStrip/available.py
    ;;
    "--debug")
        $EXECUTE $ROOT/Interfaces/start.py debug
    ;;
    "--down-interfaces")
        $EXECUTE $ROOT/Logs/down.py
    ;;
    "--edit-rack")
        $EXECUTE $ROOT/Racks/edit.py
    ;;
    "--help")
        help
    ;;
    "--interfaces")
        $EXECUTE $ROOT/Interfaces/active.py
    ;;
    "--log")
        $EXECUTE $ROOT/Logs/log.py
    ;;
    "--led-calibration")
        $EXECUTE $ROOT/LEDStrip/pruebaLEDs.py
    ;;
    "--led-calibration-fast")
        $EXECUTE $ROOT/LEDStrip/pruebaLEDs_fast.py
    ;;
    "--racks")
        $EXECUTE $ROOT/Racks/active.py
    ;;
    "--restart")
        $EXECUTE $ROOT/Interfaces/start.py restart
    ;;
    "--remove-interface")
        $EXECUTE $ROOT/Interfaces/remove.py
    ;;
    "--remove-rack")
        $EXECUTE $ROOT/Racks/remove.py
    ;;
    "--start")
        $EXECUTE $ROOT/Interfaces/start.py start
    ;;
    "--status")
        $EXECUTE $ROOT/Interfaces/start.py running
    ;;
    "--stop")
        $EXECUTE $ROOT/Interfaces/start.py stop 
    ;;
    *)
        help
    ;;
esac
